# -*- coding: utf-8 -*-
"""EisaarYarApp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GCIglTtfgE7yHh8OspjQsvSFs56Im3BQ
"""

import flet as ft
import sqlite3
import pandas as pd

# آدرس شیت شما (مطمئن شو ستون 'رمز عبور' اضافه شده باشد)
SHEET_URL = "https://docs.google.com/spreadsheets/d/1Os8X6r7LRv7XSjWJSjeCpNtv54rDMvv9XE_ZW-12-WA/export?format=csv"

def init_db():
    conn = sqlite3.connect("media_group.db")
    cursor = conn.cursor()
    cursor.execute('CREATE TABLE IF NOT EXISTS members (name TEXT, unit TEXT, role TEXT, level TEXT, password TEXT)')
    cursor.execute('CREATE TABLE IF NOT EXISTS tasks (id INTEGER PRIMARY KEY AUTOINCREMENT, user_name TEXT, title TEXT, is_done INTEGER)')
    conn.commit()
    conn.close()

def main(page: ft.Page):
    page.title = "پنل اختصاصی رسانه"
    page.theme_mode = ft.ThemeMode.LIGHT
    page.rtl = True
    page.window_width = 380
    page.bgcolor = "#F0F4F4"
    init_db()

    # متغیر برای ذخیره نام کاربر لاگین شده
    logged_in_user = None

    # --- تابع ورود (Login Logic) ---
    def login_attempt(e):
        nonlocal logged_in_user
        name = user_field.value
        pwd = pass_field.value

        conn = sqlite3.connect("media_group.db")
        cursor = conn.cursor()
        cursor.execute("SELECT name FROM members WHERE name=? AND password=?", (name, pwd))
        result = cursor.fetchone()
        conn.close()

        if result:
            logged_in_user = result[0]
            show_main_app()
        else:
            page.snack_bar = ft.SnackBar(ft.Text("نام کاربری یا رمز اشتباه است!"))
            page.snack_bar.open = True
            page.update()

    # --- المان‌های صفحه لاگین ---
    user_field = ft.TextField(label="نام و نام خانوادگی", border_radius=15, bgcolor=ft.colors.WHITE)
    pass_field = ft.TextField(label="رمز عبور", password=True, can_reveal_password=True, border_radius=15, bgcolor=ft.colors.WHITE)

    login_view = ft.Column([
        ft.Container(height=50),
        ft.Icon(ft.icons.LOCK_PERSON_ROUNDED, size=80, color="#2D9596"),
        ft.Text("ورود به پنل اعضا", size=24, weight="bold", color="#265073"),
        ft.Text("لطفاً اطلاعات خود را وارد کنید", color="grey"),
        ft.Container(height=20),
        user_field,
        pass_field,
        ft.ElevatedButton("ورود به حساب", on_click=login_attempt, bgcolor="#2D9596", color="white", width=200, height=50),
        ft.TextButton("آپدیت اولیه دیتابیس (نیاز به اینترنت)", on_click=lambda _: sync_data())
    ], horizontal_alignment=ft.CrossAxisAlignment.CENTER)

    # --- نمایش اپلیکیشن اصلی بعد از ورود ---
    def show_main_app():
        page.clean()
        page.add(
            ft.AppBar(title=ft.Text(f"خوش آمدی، {logged_in_user}"), bgcolor="#2D9596", color="white"),
            ft.Tabs(
                selected_index=0,
                tabs=[
                    ft.Tab(text="وظایف من", icon=ft.icons.CHECK_BOX, content=personal_tasks_view()),
                    ft.Tab(text="چت‌بات", icon=ft.icons.SMART_TOY, content=ft.Text("در حال ساخت...")),
                ], expand=1
            )
        )
        page.update()

    # --- بخش وظایف اختصاصی (فیلتر شده برای هر کاربر) ---
    def personal_tasks_view():
        return ft.Column([
            ft.Padding(padding=10),
            ft.Text(f"لیست تسک‌های {logged_in_user}", weight="bold"),
            # اینجا کد تسک‌هایی که قبلاً نوشتیم اضافه می‌شود با شرط user_name = logged_in_user
        ])

    # تابع سینک کردن (برای اولین بار یا آپدیت رمزها)
    def sync_data():
        try:
            df = pd.read_csv(SHEET_URL)
            conn = sqlite3.connect("media_group.db")
            df.to_sql("members", conn, if_exists="replace", index=False)
            conn.close()
            page.snack_bar = ft.SnackBar(ft.Text("دیتابیس آپدیت شد. حالا می‌توانید لاگین کنید."))
        except:
            page.snack_bar = ft.SnackBar(ft.Text("خطا در اتصال! ابتدا اینترنت را چک کنید."))
        page.snack_bar.open = True
        page.update()

    # شروع برنامه با صفحه لاگین
    page.add(ft.Container(content=login_view, padding=30))

ft.app(target=main, view=ft.AppView.WEB_BROWSER)